language: python

sudo: false

python:
   # - "2.7"
   # - "3.5"
   - "3.6"
os:
  - linux

install:
  - pip install tox

script: tox

# add student to a blocklist (it has the uncompleted exercise exceptions)
branches:
  except:
  - student
